services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  backend:
    build: ./backend
    container_name: backend
    env_file:
      - ./backend/.env
    ports:
      - "4000:4000"
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_BASE_URL: http://localhost:4000/api/v1
    container_name: frontend
    env_file:
      - ./frontend/.env
    ports:
      - "3000:3000"
    depends_on:
      - backend
volumes:
  mongodata: